/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Db {
  constructor(path: string)
  transSet(src: string, to: string, txt: string): void
  trans(src: string, to: string): Uint8Array | null
}
