/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Db {
  constructor(path: string)
  transSet(to: number, src: string, txt: string): void
  trans(to: number, src: string): Uint8Array | null
}
